#!/usr/bin/env python

"""
Query request ID.
"""

import logging

LOGGER = None

def configure_logging(log_level=logging.INFO):
    """
    Configure logging for this script.
    :args log_level: logging level to set
    """
    global LOGGER
    LOGGER = logging.getLogger('query_request_id')
    LOGGER.setLevel(log_level)
    console_handler = logging.StreamHandler()
    console_handler.setLevel(log_level)
    formatter = logging.Formatter(
        '%(asctime)s - %(name)s.%(funcName)s, line %(lineno)d - \
%(levelname)s - %(message)s'
        )
    console_handler.setFormatter(formatter)
    LOGGER.addHandler(console_handler)
    LOGGER.debug('Starting init of %s', 'query_request_id')

def main():
    """
    Called if run from command line.
    """
    import argparse
    parser = argparse.ArgumentParser(
        description='Queries request ID and prints JSON status'
        )
    parser.add_argument(
        '--url', nargs=1, dest='url', required=False,
        type=str,
        default='localhost:8983/solr',
        help="""The hostname or IP of the SolrCloud cluster. Default localhost:8983/solr"""
        )
    parser.add_argument(
        '-i', nargs=1, dest='request_id', required=True,
        type=str,
        help="""The request ID to be queried."""
        )
    parser.add_argument(
        '--debug', action='store_true', required=False,
        help="""Turn on debug logging."""
        )
    parser.add_argument(
        '--local_solrcloudadmin', action='store_true', required=False,
        help="""Import SolrCloudAdmin from local directory."""
        )
    args = parser.parse_args()

    if args.local_solrcloudadmin:
        import sys
        sys.path.append('solrcloudadmin')
        from solrcloudadmin import SolrCloudAdmin
    else:
        from solrcloudadmin import SolrCloudAdmin

    solr_cloud = None
    if args.debug:
        configure_logging(log_level=logging.DEBUG)
        solr_cloud = SolrCloudAdmin(url=args.url, log_level=logging.DEBUG)
    else:
        configure_logging(log_level=logging.INFO)
        solr_cloud = SolrCloudAdmin(url=args.url, log_level=logging.INFO)

    request_id = args.request_id[0]

    data = solr_cloud.get_request_status(request_id)
    solr_cloud.pretty_print(data)

if __name__ == '__main__':
    main()
