#!/usr/bin/env python3

"""
Provide collection counts and unhealthy collection details
"""

import logging
import argparse

from tqdm import tqdm
from solrcloudadmin.collections_api import CollectionsApi
from solrcloudadmin.scripts_library import ScriptsLibrary

SCRIPTS_LIBRARY = ScriptsLibrary()

def parse_arguments():
    """
    Parse command line arguments.
    """
    parser = argparse.ArgumentParser(
        description='Get colleciton counts (per node) and unhealthy collections'
        )
    parser = SCRIPTS_LIBRARY.additional_arguments(parser)
    return parser.parse_args()

def summary(state_summary_totals, state):
    """
    Collect totals of different state types
    """
    if state not in state_summary_totals:
        state_summary_totals[state] = 1
    else:
        state_summary_totals[state] += 1
    return state_summary_totals

def main():
    """
    Main function to be called if run as a script
    """
    # Load command line arguments
    args = parse_arguments()
    # Load configuration file
    config = SCRIPTS_LIBRARY.load_configuation_files(args.config[0])

    profile = args.profile[0]
    solr_cloud_url = '%s' % (config[profile]['solrcloud'])
    zookeeper_urls = '%s' % (config[profile]['zookeeper'])

    log_level = logging.INFO
    if args.debug:
        log_level=logging.DEBUG

    # Configure solr library
    solr = CollectionsApi(solr_cloud_url=solr_cloud_url, zookeeper_urls=zookeeper_urls, log_level=log_level, timeout=300)

    unhealthy_collections = list()
    core_state_summary = dict()
    collection_state_summary = dict()
    solrcloud_nodes = dict()

    for collection in tqdm(solr.zookeeper_list_collections(), leave=True):
        response = solr.get_collection_state(collection)
        for shard_name, shard_data in response[0][collection]['shards'].items():
            collection_state_summary = summary(collection_state_summary, shard_data['state'])

            if shard_data['state'] != 'active':
                unhealthy_collections.append((collection, shard_name, shard_data))

            for replica_name, replica_data in shard_data['replicas'].items():
                core_state_summary = summary(core_state_summary, replica_data['state'])

                if replica_data['node_name'] in solrcloud_nodes:
                    solrcloud_nodes[replica_data['node_name']] += 1
                else:
                    solrcloud_nodes[replica_data['node_name']] = 1

                if replica_data['state'] != 'active':
                    unhealthy_collections.append((collection, shard_name, replica_name, replica_data))

    print('Collection counts')
    for key in sorted(solrcloud_nodes.keys()):
        print(key, solrcloud_nodes[key])

    print('\nUnhealthy collections')
    for collection in unhealthy_collections:
        print(collection)
    print()

    final_total = 0
    print('Collection State Summary')
    for state, total in collection_state_summary.items():
        print('{} {}'.format(state, total))
        final_total += total
    print('total {}'.format(final_total))
    print()

    final_total = 0
    print('Core State Summary')
    for state, total in core_state_summary.items():
        print('{} {}'.format(state, total))
        final_total += total
    print('total {}'.format(final_total))

if __name__ == '__main__':
    main()
