#!/usr/bin/env python3

"""
Delete a shard's replica from a collection
"""

import sys
import logging
import argparse
from configparser import ConfigParser, ExtendedInterpolation

from solrcloudadmin import CollectionsApi, ScriptsLibrary

SCRIPTS_LIBRARY = ScriptsLibrary()

def parse_arguments():
    """
    Parse command line arguments.
    """
    parser = argparse.ArgumentParser(
        description='Get colleciton count for each live node in the cluster'
        )
    parser = SCRIPTS_LIBRARY.additional_arguments(parser)
    parser.add_argument(
        '--collection', '-c', nargs=1, dest='collection', required=True,
        type=str,
        help="""Collection to delete shard's replica from"""
        )
    parser.add_argument(
        '--shard', '-s', nargs=1, dest='shard', required=True,
        type=str,
        help="""Collection's shard to delete the replica from"""
        )
    parser.add_argument(
        '--replica', '-r', nargs=1, dest='replica', required=True,
        type=str,
        default=None,
        help="""Collection's shard's replica to delete"""
        )
    return parser.parse_args()

def main():
    """
    Main function to be called if run as a script
    """
    # Load command line arguments
    args = parse_arguments()
    # Load configuration file
    config = SCRIPTS_LIBRARY.load_configuation_files(args.config[0])

    profile = args.profile[0]
    solr_cloud_url = '%s' % (config[profile]['solrcloud'])
    zookeeper_urls = '%s' % (config[profile]['zookeeper'])

    log_level = logging.INFO
    if args.debug:
        log_level=logging.DEBUG

    # Configure solr library
    solr = CollectionsApi(solr_cloud_url=solr_cloud_url, zookeeper_urls=zookeeper_urls, log_level=log_level, timeout=300)

    collection = args.collection[0]
    shard = args.shard[0]
    replica = args.replica[0]

    response = solr.delete_replica(collection=collection, shard=shard, replica=replica)
    try:
        print(response.json())
    except Exception as e:
        print(response.text)
        print(e)

if __name__ == '__main__':
    main()
