#!/usr/bin/env python3

"""
View collection state
"""

import sys
import logging
import json
import argparse
from configparser import ConfigParser, ExtendedInterpolation

from solrcloudadmin import CollectionsApi, ScriptsLibrary

SCRIPTS_LIBRARY = ScriptsLibrary()

def parse_arguments():
    """
    Parse command line arguments.
    """
    parser = argparse.ArgumentParser(
        description='Get colleciton count for each live node in the cluster'
        )
    parser = SCRIPTS_LIBRARY.additional_arguments(parser)
    parser.add_argument(
        '--collection', '-c', nargs=1, dest='collection', required=True,
        type=str,
        help="""Collection to delete shard's replica from"""
        )
    return parser.parse_args()

def main():
    """
    Main function to be called if run as a script
    """
    # Load command line arguments
    args = parse_arguments()
    # Load configuration file
    config = SCRIPTS_LIBRARY.load_configuation_files(args.config[0])

    profile = args.profile[0]
    solr_cloud_url = '%s' % (config[profile]['solrcloud'])
    zookeeper_urls = '%s' % (config[profile]['zookeeper'])

    log_level = logging.INFO
    if args.debug:
        log_level=logging.DEBUG

    # Configure solr library
    solr = CollectionsApi(solr_cloud_url=solr_cloud_url, zookeeper_urls=zookeeper_urls, log_level=log_level, timeout=300)

    response = solr.get_collection_state(collection=args.collection[0])[0]
    print(json.dumps(response, indent=2))

if __name__ == '__main__':
    main()
