#!/usr/bin/env python3

"""
Delete replicas that are down, useful for when a node is gone
"""

import logging
import argparse

from solrcloudadmin.collections_api import CollectionsApi
from solrcloudadmin.scripts_library import ScriptsLibrary

SCRIPTS_LIBRARY = ScriptsLibrary()

def parse_arguments():
    """
    Parse command line arguments.
    """
    parser = argparse.ArgumentParser(
        description='Delete replicas that are in a down state, useful for cleaning up replicas on a SolrCloud node that no longer exists'
        )
    parser = SCRIPTS_LIBRARY.additional_arguments(parser)
    return parser.parse_args()

def main():
    """
    Main function to be called if run as a script
    """
    # Load command line arguments
    args = parse_arguments()
    # Load configuration file
    config = SCRIPTS_LIBRARY.load_configuation_files(args.config[0])

    profile = args.profile[0]
    solr_cloud_url = '%s' % (config[profile]['solrcloud'])
    zookeeper_urls = '%s' % (config[profile]['zookeeper'])

    log_level = logging.INFO
    if args.debug:
        log_level=logging.DEBUG

    # Configure solr library
    solr = CollectionsApi(solr_cloud_url=solr_cloud_url, zookeeper_urls=zookeeper_urls, log_level=log_level)

    collection_list = None
    if args.collection:
        collection_list = args.collection
    else:
        collection_list = solr.zookeeper_list_collections()

    for collection in collection_list:
        for shard_name, shard_data in solr.get_collection_state(collection)[0][collection]['shards'].items():
            if shard_data['state'] != 'active':
                print('''Won't work on shards that aren't active''', collection, shard_name, shard_data)
                break

            can_delete = False
            to_delete = list()
            for replica_name, replica_data in shard_data['replicas'].items():
                if replica_data['state'] == 'down':
                    to_delete.append(replica_name)
                elif replica_data['state'] == 'active':
                    can_delete = True

            if can_delete:
                print(collection, shard_name, to_delete)
                for replica in to_delete:
                    response = solr.delete_replica(collection=collection, shard=shard_name, replica=replica)
                    print(response.raw)
            else:
                print(collection)

if __name__ == '__main__':
    main()
