#!/usr/bin/env python3

"""
Move a collection off a host to another host
"""

import logging
import argparse

from solrcloudadmin.collections_api import CollectionsApi
from solrcloudadmin.scripts_library import ScriptsLibrary

SCRIPTS_LIBRARY = ScriptsLibrary()

def parse_arguments():
    """
    Parse command line arguments.
    """
    parser = argparse.ArgumentParser(
        description='Move a collection from one host to another'
        )
    parser = SCRIPTS_LIBRARY.additional_arguments(parser)
    parser.add_argument(
        '--collection', '-c', nargs=1, dest='collection', required=True,
        type=str,
        help="""Collection name to move"""
        )
    parser.add_argument(
        '--source-node', '-s', nargs=1, dest='source_node', required=True,
        type=str,
        help="""Node to remove collection from"""
        )
    parser.add_argument(
        '--destination-node', '-d', nargs=1, dest='destination_node', required=False,
        type=str,
        help="""Node to place replica on, if not specified then ranodm node will be choosen"""
        )
    parser.add_argument(
        '--dry-run', '-n', action='store_true', required=False,
        help="""Goes through all the steps except adding the replica"""
        )
    return parser.parse_args()

def move_collection(solr, collection, source_node, destination_node=None):
    """
    Move the specified collection to the new host
    """
    # Get a list of all shards and replicas on this host
    collection_state = solr.get_collection_state(collection=collection)[0][collection]

    # Add replicas for all the shards on this host to other hosts
    for shard, replicas in collection_state['shards'].items():
        for replica_name, replica_data in replicas['replicas'].items():
            if replica_data['node_name'] == source_node:
                result = solr.add_replica(collection=collection, shard=shard, node=destination_node)
                if 'success' not in result.json():
                    raise Exception({'Msg': 'success not found in result', 'result': result.content})
                else:
                    print('replica added')
                    print('result: {}'.format(result.json()['success']))
    # Delete the collection off this host
    collection_state = solr.get_collection_state(collection=collection)[0][collection]
    for shard, replicas in collection_state['shards'].items():
        for replica_name, replica_data in replicas['replicas'].items():
            if replica_data['node_name'] == source_node:
                print(replica_name, replica_data)
                result = solr.delete_replica(collection=collection, shard=shard, replica=replica_name)
                print(result.json())

def main():
    """
    Main function to be called if run as a script
    """

    # Load command line arguments
    args = parse_arguments()

    # Load configuration file
    config = SCRIPTS_LIBRARY.load_configuation_files(args.config[0])

    profile = args.profile[0]
    solr_cloud_url = '%s' % (config[profile]['solrcloud'])
    zookeeper_urls = '%s' % (config[profile]['zookeeper'])

    log_level = logging.INFO
    if args.debug:
        log_level=logging.DEBUG

    if args.destination_node:
        destination_node = args.destination_node[0]
    else:
        destination_node = None

    # Configure solr library
    solr = CollectionsApi(solr_cloud_url=solr_cloud_url, zookeeper_urls=zookeeper_urls, log_level=log_level)
    move_collection(solr=solr, collection=args.collection[0], source_node=args.source_node[0], destination_node=destination_node)

if __name__ == '__main__':
    main()
